using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Ship monitor UI for choosing the next planet before launching.
///
/// Project rule:
/// - Planet candidates (A/B offers) are generated by PlanetSelectionBootstrapper when the ship scene starts.
/// - This UI only reads PlanetSelectionState and lets the player lock a choice.
/// </summary>
public class PlanetSelectionMonitorUI : MonoBehaviour
{
    [Header("Option A UI")]
    public TMP_Text optionATitle;
    [Tooltip("Option A primary detail line. In the current UI this is used for Reward.")]
    public TMP_Text optionADetails;

    [Tooltip("Option A secondary detail text shown under Reward (optional).")]
    public TMP_Text optionADetails2;
    public Button optionAButton;

    [Header("Option B UI")]
    public TMP_Text optionBTitle;
    [Tooltip("Option B primary detail line. In the current UI this is used for Reward.")]
    public TMP_Text optionBDetails;

    [Tooltip("Option B secondary detail text shown under Reward (optional).")]
    public TMP_Text optionBDetails2;
    public Button optionBButton;

    // =========================
    // NEW: Manual Image bindings
    // =========================
    [System.Serializable]
    public class CargoCategoryImageBinding
    {
        public ItemCategory category;
        public Image image; // <-- 그냥 UI Image
    }

    [Header("Contract Cargo Icons (Manual UI Images)")]
    [Tooltip("Option A: category -> Image. Default OFF, turn ON (alpha 255) only if contract contains that category.")]
    public List<CargoCategoryImageBinding> optionACargoCategoryImages = new List<CargoCategoryImageBinding>();

    [Tooltip("Option B: category -> Image. Default OFF, turn ON (alpha 255) only if contract contains that category.")]
    public List<CargoCategoryImageBinding> optionBCargoCategoryImages = new List<CargoCategoryImageBinding>();

    [Tooltip("Alpha when the category exists in contract. 255 = fully opaque.")]
    [Range(0, 255)] public int cargoIconAlphaOn = 255;
    [Range(0, 255)] public int cargoIconAlphaOff = 10;

    // =========================
    // LEGACY (optional): prefab icon system (kept for compatibility)
    // =========================
    [Header("Contract Cargo Icons (Legacy / Optional)")]
    [Tooltip("Icon library for each ItemCategory. If null, cargo icons will not render.")]
    public ItemCategoryIconLibrary cargoIconLibrary;

    [Tooltip("Prefab that has CategoryIconCountWidget (Image + TMP count).")]
    public GameObject cargoCategoryIconPrefab;

    [Tooltip("Root transforms where cargo category icons will be placed.")]
    public Transform optionACargoIconsRoot;
    public Transform optionBCargoIconsRoot;

    [Header("Cargo Icon Layout (Legacy)")]
    [Tooltip("If the cargo icons root has no LayoutGroup, icons will be positioned manually so they line up inside the bar.")]
    public bool autoLayoutCargoIcons = true;

    [Min(0f)] public float cargoIconSpacing = 34f;
    public Vector2 cargoIconStartOffset = Vector2.zero;

    [Tooltip("Force each cargo icon widget to a fixed size. Useful when using a plain Image prefab.")]
    public bool forceCargoIconSize = true;
    public Vector2 cargoIconSize = new Vector2(32f, 32f);

    [Header("Option Visuals (Bright/Dark)")]
    [Tooltip("Optional. If assigned, alpha will be adjusted to brighten/dim the selected/unselected option.")]
    public CanvasGroup optionAGroup;

    [Tooltip("Optional. If assigned, alpha will be adjusted to brighten/dim the selected/unselected option.")]
    public CanvasGroup optionBGroup;

    [Range(0f, 1f)] public float selectedAlpha = 1f;
    [Range(0f, 1f)] public float unselectedAlpha = 0.35f;

    [Header("Danger Icons (Optional)")]
    [Tooltip("Prefab for a single warning icon (red). Icon count is derived from planet riskLevel.")]
    public GameObject dangerIconPrefab;

    [Tooltip("Parent transforms that will contain the duplicated warning icons.")]
    public Transform optionADangerIconsRoot;
    public Transform optionBDangerIconsRoot;

    [Tooltip("Max warning icons. With the default 0-100 risk and 20 risk per icon, this should be 5.")]
    [Min(0)] public int maxDangerIcons = 5;

    [Header("Danger Icon Layout")]
    [Tooltip("If the danger icons root has no LayoutGroup, icons will be positioned manually so they line up inside the bar.")]
    public bool autoLayoutDangerIcons = true;

    [Min(0f)] public float dangerIconSpacing = 26f;
    public Vector2 dangerIconStartOffset = Vector2.zero;

    [Tooltip("Force each danger icon to a fixed size. Useful when using a plain Image prefab.")]
    public bool forceDangerIconSize = true;
    public Vector2 dangerIconSize = new Vector2(32f, 32f);

    [Header("Danger Rules")]
    [Tooltip("Max risk value. 0-100 by default.")]
    public int maxRisk = 100;

    [Tooltip("Each N risk adds one warning icon (ceil). 20 means: 1-20=1, 21-40=2, etc.")]
    public int riskPerIcon = 20;

    [Header("Controls")]
    public Button backButton; // same role as ESC (close)
    public TMP_Text statusText;

    [Header("Terminal")]
    [Tooltip("Optional. If assigned, closing this UI will go through the terminal controller so it can release ModalUIOpen.")]
    public MonitorTerminalUIController terminalController;

    [Header("Behavior")]
    [Tooltip("If true, pressing ESC will close this panel.")]
    public bool closeOnEscape = true;

    private PlanetSelectionState.Offer _a;
    private PlanetSelectionState.Offer _b;

    private bool _lastHasCandidates;

    private readonly List<GameObject> _dangerIconsA = new List<GameObject>();
    private readonly List<GameObject> _dangerIconsB = new List<GameObject>();

    private readonly List<CategoryIconCountWidget> _cargoIconsA = new List<CategoryIconCountWidget>();
    private readonly List<CategoryIconCountWidget> _cargoIconsB = new List<CategoryIconCountWidget>();

    private readonly Dictionary<ItemCategory, int> _tmpCounts = new Dictionary<ItemCategory, int>();

    private void OnEnable()
    {
        if (!terminalController)
            terminalController = GetComponentInParent<MonitorTerminalUIController>(true);
        if (!terminalController)
            terminalController = FindObjectOfType<MonitorTerminalUIController>(true);

        WireButtons();

        PlanetSelectionState.Changed -= OnStateChanged;
        PlanetSelectionState.Changed += OnStateChanged;

        // 기본: 수동 아이콘은 전부 꺼둠
        SetManualCargoImagesToOff(optionACargoCategoryImages);
        SetManualCargoImagesToOff(optionBCargoCategoryImages);

        LoadFromState();
        RefreshUI();
        _lastHasCandidates = PlanetSelectionState.HasCandidates;
    }

    private void OnDisable()
    {
        PlanetSelectionState.Changed -= OnStateChanged;
    }

    private void Update()
    {
        if (closeOnEscape && Input.GetKeyDown(KeyCode.Escape))
            Close();

        bool hasCandidatesNow = PlanetSelectionState.HasCandidates;
        if (hasCandidatesNow != _lastHasCandidates)
        {
            _lastHasCandidates = hasCandidatesNow;
            LoadFromState();
            RefreshUI();
        }
    }

    private void OnStateChanged()
    {
        LoadFromState();
        RefreshUI();
    }

    private void WireButtons()
    {
        if (optionAButton != null)
        {
            optionAButton.onClick.RemoveListener(OnPickA);
            optionAButton.onClick.AddListener(OnPickA);
        }

        if (optionBButton != null)
        {
            optionBButton.onClick.RemoveListener(OnPickB);
            optionBButton.onClick.AddListener(OnPickB);
        }

        if (backButton != null)
        {
            backButton.onClick.RemoveListener(Close);
            backButton.onClick.AddListener(Close);
        }
    }

    public void Close()
    {
        if (terminalController != null)
            terminalController.Close();
        else
            gameObject.SetActive(false);
    }

    private void LoadFromState()
    {
        if (!PlanetSelectionState.HasCandidates)
        {
            _a = default;
            _b = default;
            return;
        }

        _a = PlanetSelectionState.GetCandidate(0);
        _b = PlanetSelectionState.GetCandidate(1);
    }

    private void RefreshUI()
    {
        bool hasCandidates = PlanetSelectionState.HasCandidates;
        bool hasSelection = PlanetSelectionState.HasSelection;
        bool locked = PlanetSelectionState.HasConfirmed;
        int sel = PlanetSelectionState.GetSelectedIndex();

        if (!hasCandidates)
        {
            if (optionATitle != null) optionATitle.text = "—";
            if (optionBTitle != null) optionBTitle.text = "—";
            if (optionADetails != null) optionADetails.text = string.Empty;
            if (optionADetails2 != null) optionADetails2.text = string.Empty;
            if (optionBDetails != null) optionBDetails.text = string.Empty;
            if (optionBDetails2 != null) optionBDetails2.text = string.Empty;

            if (optionAButton != null) optionAButton.interactable = false;
            if (optionBButton != null) optionBButton.interactable = false;

            ApplyOptionVisuals(false, -1);

            // 수동 아이콘은 전부 꺼둠
            SetManualCargoImagesToOff(optionACargoCategoryImages);
            SetManualCargoImagesToOff(optionBCargoCategoryImages);

            // 레거시 아이콘도 숨김
            EnsureCargoIcons(optionACargoIconsRoot, _cargoIconsA, null);
            EnsureCargoIcons(optionBCargoIconsRoot, _cargoIconsB, null);

            EnsureDangerIcons(optionADangerIconsRoot, _dangerIconsA, 0);
            EnsureDangerIcons(optionBDangerIconsRoot, _dangerIconsB, 0);

            if (statusText != null)
                statusText.text = "Loading routes...";

            return;
        }

        if (optionATitle != null) optionATitle.text = BuildTitle(_a, index: 0, sel, locked);
        if (optionBTitle != null) optionBTitle.text = BuildTitle(_b, index: 1, sel, locked);

        ApplyOfferText(optionADetails, optionADetails2, _a);
        ApplyOfferText(optionBDetails, optionBDetails2, _b);

        if (optionAButton != null) optionAButton.interactable = !locked;
        if (optionBButton != null) optionBButton.interactable = !locked;

        ApplyOptionVisuals(hasSelection, sel);

        // ---- Contract cargo icons ----
        // 우선순위: 수동 바인딩(Image) > 레거시(프리팹 생성)
        bool useManualA = optionACargoCategoryImages != null && optionACargoCategoryImages.Count > 0;
        bool useManualB = optionBCargoCategoryImages != null && optionBCargoCategoryImages.Count > 0;

        if (useManualA)
            ApplyManualCargoImages(optionACargoCategoryImages, _a.contract);
        else
            EnsureCargoIcons(optionACargoIconsRoot, _cargoIconsA, _a.contract);

        if (useManualB)
            ApplyManualCargoImages(optionBCargoCategoryImages, _b.contract);
        else
            EnsureCargoIcons(optionBCargoIconsRoot, _cargoIconsB, _b.contract);

        EnsureDangerIcons(optionADangerIconsRoot, _dangerIconsA, GetWarningIconCount(_a));
        EnsureDangerIcons(optionBDangerIconsRoot, _dangerIconsB, GetWarningIconCount(_b));

        if (statusText != null)
        {
            if (!hasSelection)
                statusText.text = "Pick A or B (locks immediately).";
            else if (locked)
                statusText.text = "Destination locked. Pull the lever to launch.";
            else
                statusText.text = "Pick A or B (locks immediately).";
        }
    }

    // =========================
    // Manual cargo image logic
    // =========================
    private void SetManualCargoImagesToOff(List<CargoCategoryImageBinding> bindings)
    {
        if (bindings == null) return;

        float aOff = Mathf.Clamp01(cargoIconAlphaOff / 255f);

        for (int i = 0; i < bindings.Count; i++)
        {
            var b = bindings[i];
            if (b == null || b.image == null) continue;

            // 자리 유지를 위해 항상 활성화
            b.image.gameObject.SetActive(true);

            var c = b.image.color;
            c.a = aOff;
            b.image.color = c;
        }
    }


    private void ApplyManualCargoImages(List<CargoCategoryImageBinding> bindings, DeliveryContractDefinition contract)
    {
        if (bindings == null) return;

        ContractCargoCategoryUtil.BuildCategoryCounts(contract, _tmpCounts);

        float aOn = Mathf.Clamp01(cargoIconAlphaOn / 255f);
        float aOff = Mathf.Clamp01(cargoIconAlphaOff / 255f);

        for (int i = 0; i < bindings.Count; i++)
        {
            var b = bindings[i];
            if (b == null || b.image == null) continue;

            // 자리 유지를 위해 항상 켜둠
            b.image.gameObject.SetActive(true);

            bool inContract = false;
            if (contract != null)
                inContract = _tmpCounts.TryGetValue(b.category, out int count) && count > 0;

            var c = b.image.color;
            c.a = inContract ? aOn : aOff;   // <- 여기 핵심
            b.image.color = c;
        }
    }


    private void ApplyOptionVisuals(bool hasSelection, int sel)
    {
        if (optionAGroup == null && optionBGroup == null)
            return;

        if (!hasSelection)
        {
            if (optionAGroup != null) optionAGroup.alpha = selectedAlpha;
            if (optionBGroup != null) optionBGroup.alpha = selectedAlpha;
            return;
        }

        if (optionAGroup != null) optionAGroup.alpha = (sel == 0) ? selectedAlpha : unselectedAlpha;
        if (optionBGroup != null) optionBGroup.alpha = (sel == 1) ? selectedAlpha : unselectedAlpha;
    }

    private string BuildTitle(PlanetSelectionState.Offer offer, int index, int sel, bool locked)
    {
        string planetName = (offer.planet != null) ? offer.planet.GetDisplayLabel() : "—";
        bool isSelected = (sel == index);

        if (locked && isSelected)
            return planetName;

        return planetName;
    }

    private void ApplyOfferText(TMP_Text primary, TMP_Text secondary, PlanetSelectionState.Offer offer)
    {
        if (primary == null && secondary == null)
            return;

        string reward = BuildOfferReward(offer);
        string extra = BuildOfferExtraDetails(offer);

        if (primary != null)
        {
            if (secondary == null || secondary == primary)
            {
                if (string.IsNullOrEmpty(extra))
                    primary.text = reward;
                else
                    primary.text = reward + "\n" + extra;
            }
            else
            {
                primary.text = reward;
            }
        }

        if (secondary != null && secondary != primary)
            secondary.text = extra;
    }

    private string BuildOfferReward(PlanetSelectionState.Offer offer)
    {
        int maxReward = (offer.contract != null) ? offer.contract.ComputeMaxReward() : 0;
        return $"{maxReward}$";
    }

    private string BuildOfferExtraDetails(PlanetSelectionState.Offer offer)
    {
        if (offer.planet == null)
            return string.Empty;

        StringBuilder sb = new StringBuilder();

        if (!string.IsNullOrWhiteSpace(offer.planet.planetType))
            sb.AppendLine(offer.planet.planetType);

        return sb.ToString();
    }

    // =========================
    // Legacy prefab cargo icons (unchanged)
    // =========================
    private void EnsureCargoIcons(Transform root, List<CategoryIconCountWidget> pool, DeliveryContractDefinition contract)
    {
        if (root == null || cargoIconLibrary == null || cargoCategoryIconPrefab == null)
        {
            for (int i = 0; i < pool.Count; i++)
                if (pool[i] != null) pool[i].gameObject.SetActive(false);
            return;
        }

        ContractCargoCategoryUtil.BuildCategoryCounts(contract, _tmpCounts);

        List<ItemCategory> showCats = new List<ItemCategory>(8);
        for (int i = 0; i < ContractCargoCategoryUtil.DisplayOrder.Length; i++)
        {
            ItemCategory cat = ContractCargoCategoryUtil.DisplayOrder[i];
            if (!_tmpCounts.TryGetValue(cat, out int count) || count <= 0)
                continue;

            if (cat == ItemCategory.None)
                continue;

            Sprite icon = cargoIconLibrary.GetIcon(cat);
            if (icon == null)
                continue;

            showCats.Add(cat);
        }

        while (pool.Count < showCats.Count)
        {
            GameObject go = Instantiate(cargoCategoryIconPrefab);
            go.transform.SetParent(root, false);

            var widget = go.GetComponent<CategoryIconCountWidget>();
            if (!widget)
                widget = go.AddComponent<CategoryIconCountWidget>();

            go.SetActive(false);

            RectTransform rtNew = go.GetComponent<RectTransform>();
            if (rtNew != null)
                rtNew.localScale = Vector3.one;

            pool.Add(widget);
        }

        for (int i = 0; i < pool.Count; i++)
        {
            var widget = pool[i];
            if (!widget) continue;

            bool active = i < showCats.Count;
            widget.gameObject.SetActive(active);

            if (!active)
                continue;

            ItemCategory cat = showCats[i];
            int count = _tmpCounts.TryGetValue(cat, out int c) ? c : 0;
            Sprite icon = cargoIconLibrary.GetIcon(cat);
            widget.Set(icon, count);

            var rt = widget.GetComponent<RectTransform>();
            if (rt != null)
            {
                rt.localScale = Vector3.one;
                if (forceCargoIconSize)
                    rt.sizeDelta = cargoIconSize;
            }

            var le = widget.GetComponent<LayoutElement>();
            if (!le) le = widget.gameObject.AddComponent<LayoutElement>();
            if (forceCargoIconSize)
            {
                le.preferredWidth = cargoIconSize.x;
                le.preferredHeight = cargoIconSize.y;
                le.minWidth = cargoIconSize.x;
                le.minHeight = cargoIconSize.y;
            }
        }

        if (!autoLayoutCargoIcons)
            return;

        RectTransform rootRt = root as RectTransform;
        if (rootRt == null)
            rootRt = root.GetComponent<RectTransform>();

        if (rootRt == null)
            return;

        if (rootRt.GetComponent<LayoutGroup>() != null)
            return;

        int visibleIndex = 0;
        for (int i = 0; i < pool.Count; i++)
        {
            var widget = pool[i];
            if (!widget || !widget.gameObject.activeSelf) continue;

            var rt = widget.GetComponent<RectTransform>();
            if (!rt) continue;

            rt.anchorMin = new Vector2(0f, 0.5f);
            rt.anchorMax = new Vector2(0f, 0.5f);
            rt.pivot = new Vector2(0f, 0.5f);
            rt.localScale = Vector3.one;

            if (forceCargoIconSize)
                rt.sizeDelta = cargoIconSize;

            rt.anchoredPosition = cargoIconStartOffset + new Vector2(visibleIndex * cargoIconSpacing, 0f);
            visibleIndex++;
        }
    }

    private int GetWarningIconCount(PlanetSelectionState.Offer offer)
    {
        if (offer.planet == null) return 0;
        int risk = Mathf.Clamp(offer.planet.riskLevel, 0, maxRisk);
        return RiskToWarningIconCount(risk);
    }

    private int RiskToWarningIconCount(int risk)
    {
        if (riskPerIcon <= 0) return 0;
        if (risk <= 0) return 0;

        int icons = Mathf.CeilToInt(risk / (float)riskPerIcon);
        return Mathf.Clamp(icons, 0, maxDangerIcons);
    }

    private void EnsureDangerIcons(Transform root, List<GameObject> pool, int desiredCount)
    {
        if (root == null || dangerIconPrefab == null)
            return;

        desiredCount = Mathf.Clamp(desiredCount, 0, maxDangerIcons);

        while (pool.Count < desiredCount)
        {
            GameObject go = Instantiate(dangerIconPrefab);
            go.transform.SetParent(root, false);
            go.SetActive(false);

            var rtNew = go.GetComponent<RectTransform>();
            if (rtNew != null)
                rtNew.localScale = Vector3.one;

            pool.Add(go);
        }

        for (int i = 0; i < pool.Count; i++)
        {
            var go = pool[i];
            if (go == null) continue;

            if (go.transform.parent != root)
                go.transform.SetParent(root, worldPositionStays: false);

            go.SetActive(i < desiredCount);
        }

        if (!autoLayoutDangerIcons)
            return;

        RectTransform rootRt = root as RectTransform;
        if (rootRt == null)
            rootRt = root.GetComponent<RectTransform>();

        if (rootRt == null)
            return;

        var layoutGroup = rootRt.GetComponent<LayoutGroup>();
        if (layoutGroup != null)
        {
            if (forceDangerIconSize)
            {
                for (int i = 0; i < pool.Count; i++)
                {
                    var go = pool[i];
                    if (!go) continue;

                    var rt = go.GetComponent<RectTransform>();
                    if (rt != null)
                    {
                        rt.localScale = Vector3.one;
                        rt.sizeDelta = dangerIconSize;
                    }

                    var le = go.GetComponent<LayoutElement>();
                    if (!le) le = go.AddComponent<LayoutElement>();
                    le.preferredWidth = dangerIconSize.x;
                    le.preferredHeight = dangerIconSize.y;
                    le.minWidth = dangerIconSize.x;
                    le.minHeight = dangerIconSize.y;
                }
            }
            return;
        }

        int visibleIndex = 0;
        for (int i = 0; i < pool.Count; i++)
        {
            var go = pool[i];
            if (!go || !go.activeSelf) continue;

            var rt = go.GetComponent<RectTransform>();
            if (!rt) continue;

            rt.anchorMin = new Vector2(0f, 0.5f);
            rt.anchorMax = new Vector2(0f, 0.5f);
            rt.pivot = new Vector2(0f, 0.5f);
            rt.localScale = Vector3.one;

            if (forceDangerIconSize)
                rt.sizeDelta = dangerIconSize;

            rt.anchoredPosition = dangerIconStartOffset + new Vector2(visibleIndex * dangerIconSpacing, 0f);
            visibleIndex++;
        }
    }

    private void OnPickA()
    {
        PlanetSelectionState.TryLockSelection(0);
    }

    private void OnPickB()
    {
        PlanetSelectionState.TryLockSelection(1);
    }
}
